import { EventInfo } from "../types/viva-types";

export const EVENT_CODES: { [key: string]: EventInfo } = {
  "0": { title: "Undefined", message: "Undefined" },
  "2061": { title: "3DS flow incomplete", message: "Browser closed before authentication finished" },
  "2062": { title: "3DS validation failed", message: "Wrong password or two-factor auth code entered" },
  "2108": { title: "Payments Policy Acquiring Restriction", message: "Payments Policy Acquiring Restriction" },
  "3500": { title: "DeviceNotFound", message: "The targeted device not found." },
  "6614": { title: "IsoTransportChannelSendFailedTimeout", message: "The communication with the schema is interrupted or a time out exposed." },
  "6624": { title: "IsoTransportChannelWriteFailed", message: "The communication with the schema interrupt" },
  "6650": { title: "IsoTransportProxySendFailed", message: "An internal communication error took place on viva.com side." },
  "7001": { title: "TransactionFailed", message: "The transaction failed." },
  "10001": { title: "Refer to card issuer", message: "The issuing bank prevented the transaction" },
  "10003": { title: "Invalid merchant number", message: "Security violation (source is not correct issuer)" },
  "10004": { title: "Pick up card", message: "The card has been designated as lost or stolen" },
  "10005": { title: "Do not honor", message: "The issuing bank declined the transaction without an explanation" },
  "10006": { title: "General error", message: "The card issuer has declined the transaction as there is a problem with the card number" },
  "10007": { title: "Pick up card, special condition (fraud account)", message: "This usually means the customer’s bank has stopped the transaction because the card has been marked as fraudulent" },
  "10012": { title: "Invalid transaction", message: "The bank has declined the transaction because of an invalid format or field. This indicates the card details were incorrect" },
  "10013": { title: "Invalid amount", message: "The card issuer has declined the transaction because of an invalid format or field" },
  "10014": { title: "Invalid card number", message: "The card issuer has declined the transaction as the credit card number is incorrectly entered or does not exist" },
  "10015": { title: "Invalid issuer", message: "The card issuer doesn't exist" },
  "10019": { title: "IssuerResponseReenterTransaction", message: "The schema has declined the transaction due to authorization failure." },
  "10021": { title: "IssuerResponseNoActionTaken", message: "The schema has declined the transaction due to no client action taken." },
  "10030": { title: "Format error", message: "The card issuer does not recognise the transaction details being entered. This is due to a format error" },
  "10039": { title: "No credit account", message: "The issuer has declined the transaction as the card number used is not a credit account" },
  "10041": { title: "Lost card", message: "The card issuer has declined the transaction as the card has been reported lost" },
  "10043": { title: "Stolen card", message: "The card has been designated as lost or stolen" },
  "10046": { title: "Closed Account", message: "The transaction has been refused as the account is closed" },
  "10051": { title: "Insufficient funds", message: "The card has insufficient funds to cover the cost of the transaction" },
  "10052": { title: "No checking account", message: "The issuer has declined the transaction as the credit card number is associated to a checking account that does not exist" },
  "10053": { title: "No savings account", message: "The issuer has declined the transaction as the credit card number is associated to a savings account that does not exist" },
  "10054": { title: "Expired card", message: "The payment gateway declined the transaction because the expiration date is expired or does not match" },
  "10055": { title: "IssuerResponseIncorrectPin", message: "The issuer has responded that the PIN is incorrect" },
  "10057": { title: "Function not permitted to cardholder", message: "The card issuer has declined the transaction as the credit card cannot be used for this type of transaction" },
  "10058": { title: "Function not permitted to terminal", message: "The card issuer has declined the transaction as the credit card cannot be used for this type of transaction" },
  "10059": { title: "Suspected Fraud", message: "The issuing bank has declined the transaction as a result of suspected fraud" },
  "10061": { title: "Withdrawal limit exceeded", message: "Exceeds withdrawal amount limit" },
  "10062": { title: "Restricted card", message: "The customer's bank has declined their card" },
  "10063": { title: "Issuer response security violation", message: "Flag raised due to security validation problem" },
  "10065": { title: "Soft decline", message: "The issuer requests Strong Customer Authentication. The merchant should retry the transaction after successfully authenticating customer with 3DS first" },
  "10070": { title: "Call issuer", message: "Contact card issuer" },
  "10075": { title: "PIN entry tries exceeded", message: "Allowable number of PIN tries exceeded" },
  "10076": { title: "Invalid / non-existent 'to account' specified", message: "An invalid or non-existent 'to' account has been specified" },
  "10077": { title: "Invalid / non-existent 'from account' specified", message: "An invalid or non-existent 'from' account has been specified" },
  "10078": { title: "IssuerResponseCardBlockOrNotActivated", message: "The issuer has responded that the card is blocked or not activated" },
  "10079": { title: "Life Cycle", message: "Issuer response: 'Life Cycle' issue" },
  "10080": { title: "No financial impact", message: "This is usually returned when a reversal is sent for an authorization message that was already declined" },
  "10081": { title: "IssuerResponseDomesticDebitTransactionNotAllowed", message: "The issuer has responded that the domestic debit transaction is not allowed" },
  "10083": { title: "Fraud/Security", message: "Issuer response: 'Fraud/Security' issue" },
  "10084": { title: "Invalid Authorization Life Cycle", message: "Issuer response: 'Invalid Authorization Life Cycle' issue" },
  "10086": { title: "IssuerResponsePinValidationNotPossible", message: "The issuer has responded that the pin validation is not possible" },
  "10088": { title: "Cryptographic failure", message: "Issuer response: 'Cryptographic failure' issue" },
  "10089": { title: "Unacceptable PIN - Transaction Declined - Retry", message: "The entered PIN code was incorrect" },
  "10091": { title: "IssuerResponseIssuerUnavailable", message: "The transaction declined because the issuer did not expose any response" },
  "10093": { title: "Transaction cannot be completed; violation of law", message: "The issuing bank has recognised (or has been informed of) a legal violation on the part of the credit card user, and assets have been frozen" },
  "10094": { title: "IssuerResponseDuplicateTransmissionDetected", message: "The schema declined the transaction due to duplicate transmission." },
  "10096": { title: "System malfunction", message: "A temporary error occurred during the transaction" },
  "10199": { title: "IssuerResponseEmpty", message: "The transaction failed because the issuer exposed empty response" },
  "10200": { title: "Generic error", message: "A temporary error occurred during the transaction" },
  "10201": { title: "IssuerResponseForceReversal", message: "The transaction reversed because the issuer exposed as response force reversal" },
  "10210": { title: "Invalid CVV", message: "The CVV2 code entered is incorrect" },
  "10211": { title: "Negative Online CAM, dCVV, iCVV, CVV, or CAVV results or Offline PIN Authentication", message: "Issuer response: 'Negative Online CAM, dCVV, iCVV, CVV, or CAVV results or Offline PIN Authentication' issue" },
  "10212": { title: "Blocked Card", message: "Transaction from new cardholder, and card not properly unblocked" },
  "10213": { title: "Revocation of authorization order", message: "The cardholder has revoked authorisation for future payments to a particular merchant" },
  "10214": { title: "Verification Data Failed", message: "Issuer response: 'Verification Data Failed' issue" },
  "10215": { title: "Policy", message: "The transaction has been refused due to a policy reason" },
  "10216": { title: "Invalid/nonexistent account specified", message: "The issuing bank of the credit card could not find an account for the card" },
  "10221": { title: "IssuerResponseVisaNoSuchIssuerFirst8Digits", message: "The schema has declined the transaction because the first 8 digits of an account number do not relate to an issuing identifier." },
  "10222": { title: "IssuerResponseVisaLostCardPickUp", message: "The issuer has flagged this card as lost" },
  "10223": { title: "IssuerResponseVisaStolenCardPickUp", message: "The issuer has flagged this card as stolen" },
  "10224": { title: "IssuerResponseVisaClosedAccount", message: "The issuer has flagged that the bank account linked to this card, as not active" },
  "10300": { title: "IssuerResponseScaRequestedOnlinePinSupported", message: "The issuer has declined the transaction due to a Strong Customer Authentication request" },
  "10301": { title: "Soft decline", message: "The issuer requests Strong Customer Authentication. The merchant should retry the transaction after successfully authenticating customer with 3DS first" },
  "10302": { title: "IssuerResponseScaRequestedSecondTap", message: "The issuer has declined the transaction because it requires a second tap due to Strong Customer Authentication" },
  "10400": { title: "IssuerResponseBancontactUseChip", message: "The issuer has declined the transaction because Chip is required" },
  "10401": { title: "IssuerUnavailable", message: "The transaction has failed because the issuer is not available" },
  "18202": { title: "AcquiringCartesBancairesVoidValidationFailed", message: "The void with Cartes Bancaires can not completed due to validation failure" },
  "100918": { title: "PayconiqPaymentStatusExpired", message: "The transaction failed because it expired" },
  "100919": { title: "PayconiqPaymentStatusCanceled", message: "The transaction failed because it cancelled" },
  "101003": { title: "PaymentMethodsParseResponseFailed", message: "The schema declined the transaction because the payment method was parsed back from the host is unknown." },
  "101407": { title: "KlarnaStatusCancelled", message: "The transaction failed because it cancelled" }
};

export const ECI_CODES: { [key: string]: { title: string } } = {
  "0": { title: "Unspecified" },
  "1": { title: "Authenticated" },
  "2": { title: "No 3DS" },
  "3": { title: "Attempt or not enrolled" },
  "5": { title: "Full 3ds (Visa/Amex/Diners/JCB/Discover)" },
  "6": { title: "Attempted (Visa/Amex/Diners/JCB/Discover)" },
  "7": { title: "Non Authenticated / TRA Exemption via 3ds (Visa/Amex/Diners/JCB/Discover)" },
  "20": { title: "Card based 3DS (Bancontact)" },
  "50": { title: "QR Code Based Authentication (Bancontact)" },
  "51": { title: "URL Intent Authentication (Bancontact)" },
  "210": { title: "Full 3ds (MasterCard/Maestro)" },
  "211": { title: "Attempted (MasterCard/Maestro)" },
  "212": { title: "Full 3DS - pan based transaction (MasterCard/Maestro)" },
  "242": { title: "Full 3DS - tokenized (MasterCard/Maestro)" },
  "246": { title: "TRA Exemption via 3ds (MasterCard/Maestro)" }
};